### PR TITLE
Update loadorder for 1.94 Contact DLC

### PR DESCRIPTION
**Pull request by dedmen**
Update our requiredAddons to include all of Contact DLC.
Don't merge before 1.94.

### CODE REVIEW

**Comment by commy2** [comment]
tf is an "Enoch"?

**Comment by jonpas** [comment]
> tf is an "Enoch"?

Codename for Livonia terrain.

**Comment by ColdEvul** [comment]
Whould this effect load order of cba_settings in anyway?
I've starting this experiencing cba_settings related issues in the init.sqf in Enoch.
It complaining about variable not existing suddenly.

**Comment by PabstMirror** [comment]
I don't think it would matter that much for settings, I think it's more for JAM/JR stuff.
We might want to take a look at the errors, not sure if init order changed in 1.74?
Are you using `CBA_settings_fnc_init` or `CBA_fnc_addSetting`? (later should be safer to use)

**Comment by ColdEvul** [comment]
still use the `CBA_settings_fnc_init` have not gotten to convert this yet.
I will put upp a issue if it still exist after the convert.

**Comment by dedmen** [comment]
>Whould this effect load order of cba_settings in anyway?

CBA still loads after all vanilla stuff, just like it always did.

**Pull request merged**
