### PR TITLE
remove non functional marker persistency from network component

### PR DESCRIPTION
**Pull request by commy2**
**When merged this pull request will:**
- `CBA_fnc_set/add/remove/getMarkerPersistent` do nothing in Arma 3. All global markers are always persistent
- No one uses these functions, so we should just nuke them.

### CODE REVIEW

**Comment by jonpas** [comment]
:boom:

**Comment by Killswitch00** [comment]
Ideally, we'd have a "stop using this function, it will be removed soon" helper macro similar to `DEPRECATE`. How did you determine that "no one uses these functions"?

**Comment by commy2** [comment]
>How did you determine that "no one uses these functions"?
All I did was a google search. At least no open source project is using it. All I could find is A2 scripts from 2010.
I really doubt though any closed project uses it either. The function never did anything in Arma 3. There was a need for this back in A2, but not anymore.

I could make DEPRECATED functions for these (at least for `set` and `get`, `add` and `remove` where already deprectaed years ago.) But all that would do is write an error message into the RPT, nothing else.
If someone actually uses these functions and we remove them, all that would happen is that a "undefined variable used" error is logged. So essentially the same thing as if we properly deprecate them.
I somehow feel like making a function just to exchange one error for another is not worth it.

**Comment by Killswitch00** [comment]
Ok, let's ditch them.

**Comment by dixon13** [comment]
https://github.com/CBATeam/CBA_A3/blob/64034f59109867adb92e830035b9159a7282db07/addons/common/fnc_createMarker.sqf#L62

Above is still using `CBA_fnc_setMarkerPersistent `

**Pull request merged**
