### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by jokoho48**
**When merged this pull request will:**
- Update Docs to 3.15.3

### CODE REVIEW

**Review by Killswitch00 — APPROVED** [review]

**Review by Killswitch00 — CHANGES_REQUESTED** [review]
The function index page looks strange - in the "C" part.

**Comment by jokoho48** [comment]
> 
> 
> The function index page looks strange - in the "C" part.

that has always been like that. I don't think the tool can handle it differently. even the current version has that.

**Comment by Killswitch00** [comment]
It would appear so.

**Review by Killswitch00 — APPROVED** [review]
Well, it's not worse than before.

**Pull request merged**
