### PR TITLE
add CBA_fnc_registerChatCommand

### PR DESCRIPTION
**Pull request by commy2**
**When merged this pull request will:**
- title

Documentation:
https://github.com/CBATeam/CBA_A3/wiki/Registering-Custom-Chat-Commands

### CODE REVIEW

**Comment by bux578** [comment]
what's in `_this`?

**Comment by Cuel** [comment]
Unless it's already there it would be so much useful to have the player who wrote the chat message in the parameters

**Comment by commy2** [comment]
>what's in _this?
Only one element atm. The text you entered.

>Unless it's already there it would be so much useful to have the player who wrote the chat message in the parameters
It's only local. So the event only fires when you enter something, not others.

**Comment by Cuel** [comment]
Of course 🎱

**Comment by Dorbedo** [comment]
What is the state of this feature? It could be handy.

**Comment by commy2** [comment]
@Dorbedo I wanted to make some kind of framework where you can define custom commands and optional parameters are passed to the function.

```
#customcommand argument1 argument2
```

The framework would also handle command availability (everyone, admin (voted), admin logged).

**Comment by commy2** [comment]
```sqf
["skipTime", {
    parseNumber (_this select 0) remoteExec ["skipTime"];
}, "admin"] call CBA_fnc_registerChatCommand;

#skipTime 6
```

```sqf
["killAll", {
    params [["_side", "players"]];

    private _killList = allUnits;

    switch (toLower _side) do {
        case "west": {
            _killList = _killList select {side group _x == west};
        };
        case "east": {
            _killList = _killList select {side group _x == east};
        };
        case "independant": {
            _killList = _killList select {side group _x == independant};
        };
        case "civilian": {
            _killList = _killList select {side group _x == civilian};
        };
        case "players": {
            _killList = _killList select {side group _x == civilian};
        };
        default {
            _killList = [];
        };
    };

    { _x setDamage 1 } forEach _killList;
}] call CBA_fnc_registerChatCommand

#killall west
#killall players
```

**Comment by commy2** [comment]
doc in OP

**Comment by commy2** [comment]
```
baermitumlaut [19:14] 
https://github.com/CBATeam/CBA_A3/blob/4d7a022eec8d8671abcb89f63f9791daeaea1fa2/addons/events/XEH_postInit.sqf#L60
that `isNil` should not be needed due to params
GitHub
CBATeam/CBA_A3
CBA_A3 - Community Base Addons for Arma 3
 

[19:15]  
params in the addEh stuff

[19:15]  
https://github.com/CBATeam/CBA_A3/blob/4d7a022eec8d8671abcb89f63f9791daeaea1fa2/addons/events/fnc_registerChatCommand.sqf#L34 (edited)

[19:15]  
^ there

[19:16]  
https://github.com/CBATeam/CBA_A3/blob/4d7a022eec8d8671abcb89f63f9791daeaea1fa2/addons/events/XEH_postInit.sqf#L63-L69 (edited)

[19:16]  
^ i think `private ARRAY` might look a little nicer but whatever
```

**Pull request merged**
