### PR TITLE
Add function to create UUIDs

### PR DESCRIPTION
**Pull request by BaerMitUmlaut**
**When merged this pull request will:**
- Add a simple UUID generator function

### CODE REVIEW

**Comment by commy2** [comment]
It's not unique.

**Comment by BaerMitUmlaut** [comment]
I didn't chose that name.

**Comment by commy2** [comment]
I chose to complain about it.

**Review by veteran29 — APPROVED** [review]

**Review by commy2 — CHANGES_REQUESTED** [review]
not unique

**Comment by BaerMitUmlaut** [comment]
This is an implementation that meets the RFC spec. If you want to complain about semantics, you'll have to complain to the IETF.

**Comment by commy2** [comment]
Not challenging the spec. But I am saying that this is not suited for anything in Arma.

**Comment by BaerMitUmlaut** [comment]
Arma can only do floats, so in use cases where you can potentially exceed 2^23 IDs, UUIDs would be useful. The chance of a collision is ridiculously low and way less of a risk than running out of numbers.

**Comment by commy2** [comment]
There is no need to do this when everyone already has a unique client id.

**Comment by BaerMitUmlaut** [comment]
Okay, and that helps how exactly?

**Comment by commy2** [comment]
Those are unique and therefore useful. I see no use case for this.

**Comment by BaerMitUmlaut** [comment]
Now you have one unique ID per client. What if I need 2^24 unique IDs per client? Say, for example, PFH IDs?

**Comment by commy2** [comment]
> What if I need 2^24 unique IDs per client?

I would use a function that actually provides unique ids, so not this one.

**Comment by BaerMitUmlaut** [comment]
Well, then provide a better one. They generated UUIDs are more than good enough, but feel free to prove me wrong. However I'm not willing to wait a hundred years for you to generate a duplicate.

**Review by jonpas — APPROVED** [review]
Looks fine to me.

This shouldn't be a discussion of its use, it's a standard implementation and CBA as a general library can and should provide those if there is any use for it. It is up to the library consumer to use it or not, there can even be multiple implementations of a "unique ID" generator in CBA.

**Comment by commy2** [comment]
> CBA as a general library can and should provide those if there is any use for it

What is the use case? Providing unique ids is not one of them.

**Comment by BaerMitUmlaut** [comment]
Providing an ID that is unique within the next 100 years.

**Review by jokoho48 — APPROVED** [review]

**Comment by dedmen** [comment]
You can use https://community.bistudio.com/wiki/systemTimeUTC to make it mooooooooost likely unique, down to the millisecond.

**Comment by BaerMitUmlaut** [comment]
The OS time is by default not that accurate, but sure, let's say it is.

The chances of a duplicate UUID are far lower than those of a duplicate timestamp. Imagine assigning a unique ID to every player on a server. If that code is executed at the same time for every client, the chances of an overlap are probably higher than 1/1000. Consider that this code might be executed many times, not just per day, but across multiple servers and for every session. You're going to have duplicates.

**Comment by jonpas** [comment]
Merge it @BaerMitUmlaut!

**Comment by BaerMitUmlaut** [comment]
I lack the rights to merge.

**Pull request merged**
