### PR TITLE
Update fnc_initDisplay.sqf

### PR DESCRIPTION
**Pull request by AGPHeaddikilla**
**Changed a single syntax error**
Now the inventory (lbData)-data will be loaded properly if CBA/xeh is used.

### CODE REVIEW

**Comment by commy2** [comment]
There are no semi colon after macro instructions.

**Comment by AGPHeaddikilla** [comment]
@commy2 What do you mean?

**Comment by commy2** [comment]
In SQF, statements are seperated with `;`, but the preprocessor instructions terminate on newlines. It's like SQS in that case and there you don't put semi-colons at the end of the line.

**Comment by AGPHeaddikilla** [comment]
Yeah, i know. I was just irritated.

**Comment by commy2** [comment]
I don't understand what the initial problem is. Please elaborate on that. I don't see any list boxes here.

**Comment by jonpas** [comment]
Additionally, in general pre-processor directives never use semi-colons.

**Pull request closed without merging**
