### PR TITLE
Revert "Common - Remove editor init fix"

### PR DESCRIPTION
**Pull request by jokoho48**
**When merged this pull request will:**
- Reverts changed from #1452 because it breaks usage of local variables in init/editor fields

### CODE REVIEW

**Comment by commy2** [comment]
Local variables being possible in init boxes due to the CBA hack is not reason enough to re-introduce this feature. I do not recommend this PR to be merged, but instead to tell people that local variables are not possible in init boxes, with or without ("vanilla") the newest CBA version.

**Comment by jokoho48** [comment]
> 
> 
> Local variables being possible in init boxes due to the CBA hack is not reason enough to re-introduce this feature. I do not recommend this PR to be merged, but instead to tell people that local variables are not possible in init boxes, with or without ("vanilla") the newest CBA version.

the point is that the users got used to beeing able to use private variables in init/editorCode boxes, and this will create alot of false errors/error reports to not use CBA but also other mods.

**Comment by commy2** [comment]
Or we could make dedmen implement them properly.

**Comment by jokoho48** [comment]
> 
> 
> Or we could make dedmen implement them properly.

and as long that is not done we should keep the current fix.

**Comment by PabstMirror** [comment]
@dedmen - do you know if this could be fixed in 2.06
otherwise I would say we merge

**Comment by dedmen** [comment]
wuht? local variables how?
local vars shouldn't be a problem, if they are then fixi fixi.
Need repro

**Comment by commy2** [comment]
I can't repro it in vanilla either.

**Comment by commy2** [comment]
Some more details in this German thread: https://armaworld.de/forum/thread/5089-call-befehl-in-init-feld-nach-cba-update-auf-v3-15-5-210713/?postID=40944

**Comment by dedmen** [comment]
But still no repro.
Need repro or else no fix

**Comment by jokoho48** [comment]
@dedmen 
0. load with latest CBA version v3.15.5.210713
1. place a trigger 
2. set activation to Radio Alpha
3. put this as condition
4. put snipped into activation
```sqf
private _grp1 = [getPosMarkerPos "aPosition", east, 5] call BIS_fnc_spawnGroup;
[_grp1] call CBA_fnc_taskDefend
```
5. press ok
6. see error Popup

**Comment by dedmen** [comment]
Actually the association "error displayed == doesn't work" is not correct.
The "Have to return nothing" thing was also just a bogus error, I simply removed the error message to make it work.
If you would insert a script another way it would've worked just fine.

**Comment by dedmen** [comment]
Fixed
Arma3NoOptInt_DX11_x64_FuaX18Yo9N

**Comment by commy2** [comment]
Thank you dedmen!!! Now people can finally use that editor box to the fullest, I won't have to read any myths about what a "global space" is supposed to be, we can close this pull request, and another ugly hack is gone from CBA.

**Comment by dedmen** [comment]
Programmers didn't want to implement new errors messages (neither did I) so the generic "variable namespace" error is just reused everywhere where its about variables.

Local namespace doesn't exist?
"Local variable in global space"
Missing the underscore in params?
"Local variable in global space"

**Pull request closed without merging**
