### PR TITLE
Replace BIS function call with engine command

### PR DESCRIPTION
**Pull request by Wakbub**
**When merged this pull request will:**
- Replace BIS function call `BIS_fnc_getCfgData` with with engine command `getText`.

**Links**
- [BIS_fnc_getCfgData](https://community.bistudio.com/wiki/BIS_fnc_getCfgData)
- [getText](https://community.bistudio.com/wiki/getText)

### CODE REVIEW

**Comment by dedmen** [comment]
Old one supports Number, Text and Array.
New one only supports text?

**Comment by PabstMirror** [comment]
It just does ` hintSilent format ["%1", _switchItemHintText]`
So number/array wouldn't make much sense

**Comment by Wakbub** [comment]
MRT_SwitchItemHint**Text** is always Text, so there is no point in "supporting" other types.

**Comment by commy2** [comment]
I'd rather have someone make a nicer looking ui element, possibly one that can be reused for other purposes and other mods.

**Pull request merged**
