### PR TITLE
Update JR for 1.86

### PR DESCRIPTION
**Pull request by robalo**
Convert ADR-97 rails to JR

### CODE REVIEW

**Comment by commy2** [comment]
They put it into vanilla?

**Comment by jonpas** [comment]
With next update, yes. Already in RC.

**Comment by jonpas** [comment]
Apparently they can even fit .22 rated suppressors. I am not sure if this is an off case (in which case we could support it) or a general one (in which case we would have to make it more detailed, which isn't worth it).

**Comment by Drofseh** [comment]
.22, 5.56, and 5.7 suppressors would all have the same diameter hole, so the only problems would be how it attaches and if the suppressor is strong enough to container the pressure from the blast.

I wouldn't want to use a suppressor meant for .22LR on a 5.7 or 5.56 gun unless it was robust.

**Comment by Kllrt** [comment]
I think that 7.62x39mm vz58 is missing :D

**Comment by dedmen** [comment]
Well do CZ805 magazines also fit into G36? Then I'd say just reuse it.

**Comment by Kllrt** [comment]
This is what I am not sure of, sadly...

**Comment by robalo** [comment]
What do magazines have to do with this PR ? Wrong thread ?

**Comment by dedmen** [comment]
>What do magazines have to do with this PR ?

Both are about vanilla :D

**Pull request merged**
