### PR TITLE
use mission event for PlayerConnected

### PR DESCRIPTION
**Pull request by commy2**
this replaces all `onPlayerConnected` stacked events with `PlayerConnected` mission events. it has the benefit that no mission or addon using a delayed `onPlayerConnected <CODE>` (SQF command) can overwrite our events.
WIP tag, because there currently is a bug, where the `PlayerConnected` mission event does not fire when `onPlayerConnected <CODE>` hasn't been used at least once. this is fixed according to the todays changelog, but the bug seems to be still present in the RC version uploaded to Steam.
I'll test if they fixed that next week.
backwards compatible with 1.54 / Linux, using the same method as in the `EachFrame` PR

### CODE REVIEW

**Comment by commy2** [comment]
https://forums.bistudio.com/topic/143930-general-discussion-dev-branch/?p=3003074

**Comment by esteldunedain** [comment]
This is missing the WIP label

**Comment by commy2** [comment]
PlayerConnected is still broken. I could add a work around that could be easily removed should they ever fix it.

**Comment by commy2** [comment]
could be merged now. maybe we can remove that band aid ... eventually

**Pull request merged**
