### PR TITLE
add template for a settings file inside a pbo

### PR DESCRIPTION
**Pull request by commy2**
**When merged this pull request will:**
- Adds a template that can be binarized to have a signed settings file inside a PBO
- Can be used to enforce settings for a whole repository

@PabstMirror Would that work for you?

### CODE REVIEW

**Comment by jonpas** [comment]
That looks handy!

**Comment by Killswitch00** [comment]
> ...enforce settings for a whole repository

The term "repository" is confusing. (It is not a term usually associated with playing the game. A user of CBA may wonder "what/where is a/the 'repository'?)

**Comment by commy2** [comment]
Other suggestion? "modpack" sounds weird.

**Comment by Killswitch00** [comment]
How about "static settings addon" instead of "repository settings file".

The template shows an example of an addon that can be used to enforce settings for a mod/addon collection or a mission/mission type.

**Comment by Killswitch00** [comment]
Looks good. Needs documentation that users can read (what it is, what it can be used for and so on). This could be in the form of a separate text file in the templates folder or placed in a comment header in the `config.cpp`

**Comment by Killswitch00** [comment]
Ok, so no docs then.

**Pull request merged**
