### PR TITLE
Add CBA_fnc_weekDay

### PR DESCRIPTION
**Pull request by jonpas**
**When merged this pull request will:**
- Add a function that calculates date's day of the week using a modified Rata Die method with fractional years.
- Add unit tests for the function.

### CODE REVIEW

**Comment by commy2** [comment]
CBA_fnc_weekDay

https://en.wikipedia.org/wiki/ISO_week_date

Should sunday be 0 or 7?
Is -1 a reasonable fallback?
Could the function or a variant thereof return strings, e.g. "MON"? Perhaps even (translated) stringtable entry?

**Comment by jonpas** [comment]
Whichever.
Yes.
Sure.

**Comment by jonpas** [comment]
For reference, `-1` will only return on invalid input. If we switch to 1-7 for days, invalid could also be 0.

**Review by PabstMirror — APPROVED** [review]

**Comment by PabstMirror** [comment]
`[[2101,1,1]] call CBA_fnc_weekDay;` = 0
but https://www.timeanddate.com/calendar/?year=2101 says it should be a saturday
I think it's because 2100 isn't a leap year (even though it's divisible by 4)

hopefully arma 4 is out by then, so this shouldn't really be an issue 😄 (max mission date in arma is 2050)

**Pull request merged**
