### PR TITLE
Tools - Removed deprecated Mikero tools arguments make.py

### PR DESCRIPTION
**Pull request by Dahlgren**
**When merged this pull request will:**
- Make `make.py` compatible with latest Mikero Tools updates

### CODE REVIEW

**Comment by Dahlgren** [comment]
Makepbo still fails on
https://github.com/CBATeam/CBA_A3/blob/0464ca4a143b92c71a0f8e04c0abac649841358f/addons/ee/config.cpp#L15

I've reached out to mikero about it

**Comment by jonpas** [comment]
Why were external checks suddenly removed from Mikero tools?

**Comment by Dahlgren** [comment]
It's no longer optional and will always be applied

**Comment by jonpas** [comment]
Time to finally switch CBA and ACE to HEMTT, this is getting ridiculous.

Who wants this to not be an option? Sounds terrible for quick (eg. nightly) playable builds without extracting all the used Arma files.

**Comment by commy2** [comment]
>I've reached out to mikero about it

If any questions arise for the purpose of this line; it is required and has no alternatives. However, I am not willing to participate in any discussions about this.

**Comment by Dystopian** [comment]
> It's no longer optional and will always be applied

Why not just using old version of mikero tools until moving to HEMTT?

**Comment by dedmen** [comment]
> Why not just using old version of mikero tools until moving to HEMTT?

We can certainly do that as devs, for builds and such.
But contributors who want to make a PR and test their addition, will not.

**Comment by commy2** [comment]
Even the old version cannot properly handle the scope entry.

**Pull request merged**
