### PR TITLE
add XEH to new classes

### PR DESCRIPTION
**Pull request by commy2**
probably an ongoing project

### CODE REVIEW

**Comment by commy2** [comment]
this works now without APEX. Someone with APEX please confirm that it works there too.

**Comment by commy2** [comment]
This fixes:
```
[XEH]: Plane_Civil_01_base_F does not support Extended Event Handlers! Addon: expansion
[XEH]: B_CTRG_Miller_F does not support Extended Event Handlers! Addon: expansion
```

and probably also those power lines when owning Tanoa

**Comment by jonpas** [comment]
Confirmed, this fixes all XEH support.

**Comment by jonpas** [comment]
Oh I knew I forgot to mention something, I tested with Apex.

**Pull request merged**
