### PR TITLE
remove obsolete team synch code

### PR DESCRIPTION
**Pull request by commy2**
**When merged this pull request will:**
- removes team synch code
- no longer needed as teams are synched since 1.62
- old versions are no longer supported by 3.1.0, because of changes in class inheritance for the JR component

### CODE REVIEW

**Comment by PabstMirror** [comment]
ace still uses the event 
https://github.com/acemod/ACE3/blob/master/addons/interaction/functions/fnc_joinTeam.sqf#L21

**Comment by commy2** [comment]
But does it do anything?

**Comment by PabstMirror** [comment]
We call the cba event to change fireteams, should probably just make our own

**Comment by jonpas** [comment]
Other people might be using the event as well.

**Comment by commy2** [comment]
^ this should solve it

**Pull request merged**
