### PR TITLE
Translate JAM module name into Polish

### PR DESCRIPTION
**Pull request by veteran29**
**When merged this pull request will:**
- Translate JAM module name into Polish

### CODE REVIEW

**Comment by commy2** [comment]
I brought myself to come up with something for German: https://github.com/CBATeam/CBA_A3/pull/988/files
Maybe you can do the same?

**Comment by veteran29** [comment]
I've rebased and translated module names. 

Also I've removed BOM from the files by accident, should I take care of that and revert it?

**Comment by dedmen** [comment]
>Also I've removed BOM from the files by accident, should I take care of that and revert it?

https://github.com/CBATeam/CBA_A3/blob/master/.editorconfig#L6
That looks like UTF-8 without bom. So did you remove or add?

**Comment by veteran29** [comment]
Looks like removal to me (shame github cant display it properly in diff viewer):
```
git diff HEAD^^
diff --git a/addons/jam/stringtable.xml b/addons/jam/stringtable.xml
index 6e3e5448..9f627e04 100644
--- a/addons/jam/stringtable.xml
+++ b/addons/jam/stringtable.xml
@@ -1,9 +1,10 @@
-<EF><BB><BF><?xml version="1.0" encoding="utf-8"?>
+<?xml version="1.0" encoding="utf-8"?>
 <Project name="CBA_A3">
     <Package name="JAM">
         <Key ID="STR_CBA_JR_Component">
             <English>Community Base Addons - Joint Ammo Magazines</English>
             <German>Community Base Addons - Gemeinsame Munition und Magazine</German>
+            <Polish>Community Base Addons - Wsp<C3><B3>lna Amunicja oraz Magazynki</Polish>
         </Key>
     </Package>
 </Project>
diff --git a/addons/jr/stringtable.xml b/addons/jr/stringtable.xml
index b073a0fa..4b7850a0 100644
--- a/addons/jr/stringtable.xml
+++ b/addons/jr/stringtable.xml
@@ -1,4 +1,4 @@
-<EF><BB><BF><?xml version="1.0" encoding="utf-8"?>
+<?xml version="1.0" encoding="utf-8"?>
 <Project name="CBA_A3">
     <Package name="JR">
         <Key ID="STR_CBA_JR_Component">
@@ -8,7 +8,7 @@
             <Chinese><E7><A4><BE><E7><BE><A4><E5><9F><BA><E7><A4><8E><E6><A8><A1><E7><B5><84> - <E5><85><B1><E7><94><A8><E5><B0><8E><E8><BB><8C></Chinese>
             <Chinesesimp><E7><A4><BE><E7><BE><A4><E5><9F><BA><E7><A1><80><E6><A8><A1><E7><BB><84> - <E5><85><B1><E7><94><A8><E5><AF><BC><E8><BD><A8></Chinesesimp>
             <Russian>Community Base Addons - <D0><A1><D0><B8><D1><81><D1><82><D0><B5><D0><BC><D0><B0> Joint Rails</Russian>
-            <Polish>Community Base Addons - System Joint Rails</Polish>
+            <Polish>Community Base Addons - Wsp<C3><B3>lne Szyny Monta<C5><BC>owe</Polish>
             <French>Community Base Addons - Rails d'accessoires</French>
         </Key>
         <Key ID="STR_CBA_JR_cfgweapons_muzzle_snds_h_mg">
```

**Pull request merged**
