### PR TITLE
Add MRT Accessory Functions #513

### PR DESCRIPTION
**Pull request by robalo**
**When merged this pull request will:**
- Integrate MRT Accessory Functions https://forums.bistudio.com/topic/171270-mrt-accessory-functions/
- Ref. #513

### CODE REVIEW

**Comment by jonpas** [comment]
I feel like this could use a better component name.

**Comment by robalo** [comment]
@jonpas me too, feel free to suggest a better name for it

**Comment by commy2** [comment]
should use:
```sqf
private _unit = call CBA_fnc_currentUnit;
```
and then `_unit` instead of `player`, so it works when remote controlling units with Zeus.

**Comment by Killswitch00** [comment]
Yeah, about that "accfcns" name.... How about just "accessory" (1 char longer, but more readable)?

**Comment by robalo** [comment]
I like it.

**Pull request merged**
