### PR TITLE
JR - Fix suppressor file path changes in 1.92

### PR DESCRIPTION
**Pull request by PabstMirror**
pictures changed in 1.92
it's defined fine in vanilla configs

### CODE REVIEW

**Comment by dedmen** [comment]
Now our black and green silencers have the same picture? That can't be right.

**Comment by PabstMirror** [comment]
vanilla configs are
```
class muzzle_snds_H_MG_blk_F: muzzle_snds_H_MG {
    picture = "\a3\Weapons_F_Exp\Acc\Data\UI\icon_muzzle_snds_H_MG_blk_F_ca.paa";
class muzzle_snds_H_MG_khk_F: muzzle_snds_H_MG {
    picture = "\a3\Weapons_F_Exp\Acc\Data\UI\icon_muzzle_snds_H_MG_khk_F_ca.paa";
```
and those are different images

**Comment by dedmen** [comment]
Ah we edit, not create that class. 
Why do we change the `model`? atleast for `muzzle_snds_H_MG_blk_F` we have the same as vanilla.
Also the vanilla name seems to be "Sound suppressor MG" which is same as ours.
What do we even do here? 
We don't change their model, we don't change the name, we don't change the picture.

**Comment by commy2** [comment]
Good questions. I think we may have once added these unused textures and names or something, but now BI does use them themselves. Should probably all be deleted.

**Comment by PabstMirror** [comment]
vanilla models are different (I think they were either shorter or longer) but looked fine to me

**Comment by robalo** [comment]
When I added the MG suppressor classes to CBA the vanilla ones were hidden and used either the 7.62 SCAR model or the 5.56 YHM one. IMO using the .338 model looks a lot more like an MG suppressor than those.

**Comment by robalo** [comment]
> 
> 
> Good questions. I think we may have once added these unused textures and names or something, but now BI does use them themselves. Should probably all be deleted.

Nope, they're still hidden, the only issue was picture path has changed in 1.92 for the .338 suppressors which we use as MG suppressors.

**Comment by commy2** [comment]
So everything is alright and works as expected here?

**Pull request merged**
