### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by jonpas**
**When merged this pull request will:**
- Make use of new issue template framework from GitHub.
- Split bug report, feature request and enhancement idea templates - shows up as separate buttons when creating new issues.
- Empty issue can still be created with a button below templates.

### CODE REVIEW

**Comment by commy2** [comment]
Approved, however, do we really want feature requests and "enhancement requests" on this tracker?

**Comment by jonpas** [comment]
That's up to you to provide feedback on. Depends what you want where entirely.

**Comment by commy2** [comment]
What I want is no feature requests, aside from maybe someone asking on ACE Slack and then getting the permission to open a ticket as reminder / place to info dump.

**Comment by jonpas** [comment]
[This](https://github.com/CBATeam/CBA_A3/wiki/Requesting%20new%20functionality#making-a-request) says to put feature requests on GitHub issue tracker.

**Comment by commy2** [comment]
Well, you asked me what _I_ want.

**Comment by jonpas** [comment]
Actually I didn't, I asked for your feedback. ;) And I told you there would be a discrepancy then.

**Comment by commy2** [comment]
>Actually I didn't, I asked for your feedback.

>That's _up to you_ to provide feedback on.
>Depends _what you want_ where entirely.

?

**Comment by jonpas** [comment]
Oh right, I did write that part. :joy: 

@ViperMaul your thoughts? I would personally follow what wiki already states. GitHub is also a lot more approachable.

**Pull request merged**
