### PR TITLE
Inventory - Add context menu options for pointers and optics

### PR DESCRIPTION
**Pull request by veteran29**
**When merged this pull request will:**
- title

https://i.imgur.com/1X6U2Xq.mp4

### CODE REVIEW

**Comment by commy2** [comment]
Appears to work.

**Comment by commy2** [comment]
>This branch has not been deployed

**Comment by dedmen** [comment]
How about "next state" instead just add a action for each specific state?

**Comment by veteran29** [comment]
I don't understand. Can you elaborate?

**Comment by PabstMirror** [comment]
If an attachment can be 3 different things [light, IR laser, green laser]
then list all possibilities, instead of "next/previous"

**Comment by dedmen** [comment]
Yes that.
Instead of just "Next State"
"Switch to Red Laser"

But we don't have nested context menu? So fear is that it might clutter the menu with too many entries?

**Comment by jonpas** [comment]
> But we don't have nested context menu? So fear is that it might clutter the menu with too many entries?

It might for attachments with many states, but less so if only available once attached.

**Comment by veteran29** [comment]
Feel free to do another PR then. I think it's just fluff, attachments rarely have more than 3 states, you can click through them really quickly as the menu is set to not close automatically.

**Pull request merged**
