### PR TITLE
Tools - Set build number in HEMTT release build

### PR DESCRIPTION
**Pull request by jonpas**
**When merged this pull request will:**
- Set build number in pre-build step.
- Unset build number in release step (after zipping).
- Set build number in development to `000000`.

### CODE REVIEW

**Comment by jonpas** [comment]
@commy2 please test on Windows. Resulting build should have today's build number and everything should be reset at the end of the build process (no git diffs).

**Comment by commy2** [comment]
After the fix, the only diff from build_release.bat are changed line endings in one file.


Idk if that is acceptable.

**Comment by jonpas** [comment]
Interesting, those shouldn't be changed. `mod.cpp` doesn't do that, does it?

**Comment by commy2** [comment]
Apparently not.

**Pull request merged**
