### PR TITLE
XEH - Add direct XEH support for 1.94 objects

### PR DESCRIPTION
**Pull request by PabstMirror**
Fix
```
[XEH]: Land_PortableDesk_01_animated_base_F does not support Extended Event Handlers! Addon: enoch
[XEH]: DeconShower_01_base_F does not support Extended Event Handlers! Addon: enoch
[XEH]: DeconShower_02_base_F does not support Extended Event Handlers! Addon: enoch
[XEH]: SCBACylinder_01_base_F does not support Extended Event Handlers! Addon: enoch
```

### CODE REVIEW

**Comment by dedmen** [comment]
We might have more in contact (not enoch)

**Comment by commy2** [comment]
```sqf
21:33:27 [XEH]: gm_AmmoBox_base does not support Extended Event Handlers! Addon: @GM
21:33:27 [XEH]: Land_PortableDesk_01_animated_base_F does not support Extended Event Handlers! Addon: enoch
21:33:27 [XEH]: DeconShower_01_base_F does not support Extended Event Handlers! Addon: enoch
21:33:27 [XEH]: DeconShower_02_base_F does not support Extended Event Handlers! Addon: enoch
21:33:27 [XEH]: SCBACylinder_01_base_F does not support Extended Event Handlers! Addon: enoch
21:33:27 [XEH]: VirtualAISquad does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: Particle_Base_F does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_test_F does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Bombing_Failed does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Sinkhole_Collapse does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Ammo_Burning_Intro does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Ammo_Burning_Outro does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Heli_Crash_Explosion does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_RavenPilot_Pa_01 does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_RavenPilot_Pa_02 does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Training_01_Pa_01 does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Training_02_Pa_01 does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Training_03_Pa_01 does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Loudspeaker_01 does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Loudspeaker_02 does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Loudspeaker_Ldf does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Container_Drop does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Drone_Moving_Fake_01 does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Drone_Moving_Fake_02 does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Drone_Escape_Up_Fake_01 does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Drone_Escape_Fake_02 does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Drone_ScanBeam_Fake_01 does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Drone_ScanBeam_Fake_02 does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Drone_Shout_Fake_01 does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Mothership_LiftOff_01 does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Mothership_LiftOff_02 does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Mothership_Warp_01 does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_ProbeCore_Hitpoint does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_ProbeCore_Destruction_01 does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_ProbeCore_Destruction_01_Close does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Freeroam_02_Site_Explosion_01 does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Drone_Attention does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Drone_Intimidate does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Mothership_Jammed_01 does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Mothership_Puzzle_Activate_01 does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Mothership_Puzzle_Reward_01 does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_RewardRocket_Stop_01 does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_RewardRocket_Flickr_01 does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_RewardRocket_Flickr_02 does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Probe_Expand_01 does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Probe_Retract_01 does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Probe_Expand_01_Bottom does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Probe_Retract_01_Bottom does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Probe_Calcification_01_Bottom does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Probe_Destruction does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_BombingDistant does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_SonicBoom_01 does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_SonicBoom_02 does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Probe_Extraction does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_Sfx_Probe_Extraction_Drone does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_AlienDrone_01_Strat_Start_01_SoundSet does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_AlienDrone_01_Strat_Travel_01_SoundSet does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_AlienDrone_01_Strat_End_01_SoundSet does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_AlienDrone_01_Strat_End_Land_01_SoundSet does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: SoundSetSource_AlienDrone_01_Strat_Stop_01_SoundSet does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: Alien_Extractor_01_generic_base_F does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: Alien_MatterBall_01_base_F does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: Alien_MatterBall_01_falling_F does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: B_W_Story_Protagonist_01_F does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: B_W_Story_Major_01_F does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: B_W_Story_Instructor_01_F does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: B_W_Story_Soldier_01_F does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: B_W_Story_Leader_01_F does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: O_R_Story_Capitan_01_F does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: O_R_Story_TL_01_F does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: C_Story_Scientist_01_F does not support Extended Event Handlers! Addon: @Contact
21:33:27 [XEH]: C_Story_Scientist_02_F does not support Extended Event Handlers! Addon: @Contact
```

**Comment by commy2** [comment]
`B_W_Soldier_F` is a public class. This means for every story unit there is a copy of them shown now in the editor when Contact is not started. :/

**Comment by PabstMirror** [comment]
`scope = "[0,1] select (isClass (configFile >> 'CfgPatches' >> 'a3_epoch'))";`

**Comment by commy2** [comment]
Was about to write something like that lol

**Comment by commy2** [comment]
Merge, so I can move to others?

**Pull request merged**
