### PR TITLE
JPN translation for v3.1.1

### PR DESCRIPTION
**Pull request by classicarma**
this translation is based on v3.1.1

### CODE REVIEW

**Comment by commy2** [comment]
thank you

anyone knows what this means?
```
-<?xml version="1.0" encoding="utf-8"?>
+<?xml version="1.0" encoding="utf-8"?>
```

**Comment by bux578** [comment]
@commy2 That's probably just a different line ending, if I'm not mistaken.

**Comment by jonpas** [comment]
@bux578 is probably correct. They should all be normalized though into LF, I'd double check entire file is in LF ending before merging.

**Comment by classicarma** [comment]
@commy2 I don't know is this mean, but I saw red mark at the head of <?xml version="1.0" encoding="utf-8"?> in editor screen. I was do delete it.

**Comment by Killswitch00** [comment]
Is this still up to date, now that 1.66 is out?

**Pull request merged**
