### PR TITLE
New AI function taskSearchArea

### PR DESCRIPTION
**Pull request by SilentSpike**
Adds a new function to have AI search a given marker or trigger area indefinitely with random building searches

### CODE REVIEW

**Comment by Killswitch00** [comment]
Split fixes to existing code and new additions into separate pull requests.

**Comment by SilentSpike** [comment]
:+1: Will do

**Comment by SilentSpike** [comment]
Done :smile:

**Comment by Killswitch00** [comment]
I tried the function but it causes an error immediately. Please test the code at least once before submitting a PR.

**Comment by SilentSpike** [comment]
Apologies, I actually thought I had. Will do now :+1:

**Comment by SilentSpike** [comment]
Fixed and tested :smile:

**Pull request merged**
