### PR TITLE
Translation - Add French Translations (Ai)

### PR DESCRIPTION
**Pull request by Elgin675**
**When merged this pull request will:**
- Add french translations in `ai` module.

### CODE REVIEW

**Comment by commy2** [comment]
By using these names, the objects don't appear grouped in the editor I believe.

**Comment by Elgin675** [comment]
@commy2 Indeed.
But I had no choice, to maintain consistency with the third invisible target, whose name I cannot change because it is inherited from vanilla.

If I could, I would have done this :
- Cible invisible - Soldat
- Cible invisible - Véhicule
- Cible invisible - Avion

But `CBA_B_InvisibleTarget` is inherited from vanilla (_"Soldat cible invisible"_), so I have no choice.
However, if we could rename `CBA_B_InvisibleTarget` via stringtable, I would be more than happy to change that.

**Comment by commy2** [comment]
Ah, I see. Yeah, that sucks. I would've went with the systematic name anyway, but your call.

Maybe we could just copy paste the token and edit the French entry? Not sure if it's worth that for one language, though maybe there is a point if multiple languages have that oversight.

**Comment by Elgin675** [comment]
> 
> 
> Maybe we could just copy paste the token and edit the French entry? Not sure if it's worth that for one language, though maybe there is a point if multiple languages have that oversight.

@commy2 If we could do that, that would be great :) !
I think it could also be useful for some other languages.

**Review by PabstMirror — APPROVED** [review]

**Pull request merged**
