### PR TITLE
Common - Improve remove magazine functions

### PR DESCRIPTION
**Pull request by johnb432**
**When merged this pull request will:**
- `FUNC(removeMagazine)`:
  - No longer config case sensitive.
  - Round the ammo count before treating request.
  - Because the description states that it can be run on units or vehicles, I have added vehicle support, as previously it did not support vehicles at all.
  - Code improvement brought over from ACE `ace_common_fnc_removeMagazineSpecific`
- `FUNC(removeMagazineCargo)`
  - No longer config case sensitive.
  - Round the ammo count before treating request.
  - Only removes the necessary magazines.

### CODE REVIEW

**Comment by jonpas** [comment]
All tests still pass?

**Comment by PabstMirror** [comment]
tests pass

**Comment by johnb432** [comment]
I should write new tests, as `FUNC(removeMagazine)` properly supports vehicles. Looks like no tests exist for `FUNC(removeMagazineCargo)`, I can add those.

**Comment by jonpas** [comment]
Please do. :)

**Comment by johnb432** [comment]
> Please do. :)

Done.

**Review by jonpas — APPROVED** [review]

**Comment by jonpas** [comment]
@PabstMirror Double check for me and merge?

**Review by PabstMirror — APPROVED** [review]

**Pull request merged**
