### PR TITLE
CfgFunctions for FlexiMenu ui subcomponent

### PR DESCRIPTION
**Pull request by commy2**
**When merged this pull request will:**
- close  #1054

### CODE REVIEW

**Comment by dedmen** [comment]
Bad
https://github.com/CBATeam/CBA_A3/blob/master/addons/ui/flexiMenu/fnc_openMenuByDef.sqf#L91

**Comment by commy2** [comment]
Please explain what you mean by "bad".

**Comment by dedmen** [comment]
Function doesn't exist anymore. And it shouldn't have existed previously either. I don't know why it apparently did exist at one point.

**Comment by commy2** [comment]
aha ok

**Pull request merged**
