### PR TITLE
Common - Improve CBA_fnc_addItem, Fix CBA_fnc_addMagazine return

### PR DESCRIPTION
**Pull request by Drofseh**
**When merged this pull request will:**

Improve CBA_fnc_addItem
If the unit doesn't have enough space then try to add the item to the unit's vehicle instead of always chucking it out the window onto the ground where it gets lost.

### CODE REVIEW

**Review by commy2 — COMMENTED** [review]
Changes rv from false to true when dropping items on the ground as far as I can tell.

**Comment by Drofseh** [comment]
> Changes rv from false to true when dropping items on the ground as far as I can tell.

Should change it from always returning false to returning whatever CBA_fnc_addItemCargo returns if it is called, so true if it went somewhere basically.
Ok with to change that back if you'd prefer, but this is the same behaviour that CBA_fnc_addMagazine currently has

**Comment by commy2** [comment]
Yes, because it breaks the behaviour documented in the functions header, and then also fix https://github.com/CBATeam/CBA_A3/pull/1527

**Comment by Drofseh** [comment]
Done and done

**Review by jonpas — APPROVED** [review]

**Pull request merged**
