### PR TITLE
Optimize CBA_fnc_players

### PR DESCRIPTION
**Pull request by SilentSpike**
**When merged this pull request will:**
- Use `allDeadMen` instead of `allDead`

`allDead` includes destroyed vehicles.

### CODE REVIEW

**Comment by commy2** [comment]
https://github.com/CBATeam/CBA_A3/issues/353#issue-158313664

But I never reproduced this. Will try right now.

**Comment by PabstMirror** [comment]
>NOTE: In player hosted game, the complete array of allPlayers may get delayed at the start. Use BIS_fnc_listPlayers if you need it earlier
image

**Comment by commy2** [comment]
```sqf
addMissionEventHandler ["EachFrame", {
    diag_log [diag_frameNo, allPlayers, [] call CBA_fnc_players, allPlayers isEqualTo ([] call CBA_fnc_players)];
}];
```

```
 0:39:07 [11821,[B CSCustom0:1 (Gefr. commy2)],[B CSCustom0:1 (Gefr. commy2),B CSCustom0:2 (Gefr. commy2 (2)) REMOTE],false]
```

**Comment by commy2** [comment]
But why does it use `allDead` and not `allDeadMen`?

>allDead
>Return a list of all dead units including agents and destroyed vehicles. Dead units may be in vehicles.

**Comment by SilentSpike** [comment]
Is it confirmed that the old way truly does return all players under the same circumstances in which `allPlayers` doesn't?

**Comment by commy2** [comment]
See my test. Was local hosted.

**Comment by SilentSpike** [comment]
Ah yeah, missed that :+1: Can change this to simply switch to `allDeadMen` then

**Comment by commy2** [comment]
It's still an optimization, because `isPlayer` filters out the wrecks atm. But this makes it slightly faster by not listing them in the first place.

**Pull request merged**
