### PR TITLE
Hashcleanup

### PR DESCRIPTION
**Pull request by commy2**
replaces #238 
everyone should be able to edit this now

### CODE REVIEW

**Comment by esteldunedain** [comment]
@commy2, what about changing the underlying structure to use `CBA_fnc_createNamespace`? `fnc_hashEachPair` could be based on `allVariables` which support locations.

**Comment by commy2** [comment]
hashes can use key different from strings, which is a benefit.
We can internally replace all hashes that only use strings as keys with createNamespace though (as long as they are not used in ui, i.e. the main menu)

**Comment by esteldunedain** [comment]
> hashes can use key different from strings, which is a benefit.

oh, that's true. although using `str(_object)`as key could also work for almost all cases.

> We can internally replace all hashes that only use strings as keys with createNamespace though (as long as they are not used in ui, i.e. the main menu)

Yes, that's a much safer alternative, although it's obviously much more work.

**Comment by esteldunedain** [comment]
Another possible alternative would be to add a second set of functions for "FastHashes", that only support string keys.

**Comment by esteldunedain** [comment]
> Another possible alternative would be to add a second set of functions for "FastHashes", that only support string keys.

Besides, for the first time in CBA those would be REAL hashes

**Comment by commy2** [comment]
`str(_object)` is not reliable. It changes when the vehicle var name changes or when the object switches locality (#remote tag)

**Comment by PabstMirror** [comment]
location hashes are local only (I don't think you can publicVariable a location)
I think ACRE has some stuff to serialze them, but it's not trivial.

**Comment by commy2** [comment]
ed was trying to convert objects to strings.

**Comment by esteldunedain** [comment]
Yeah, you are right. Porting current CBA Hashes to `CBA_fnc_createNamespace` doesn't seem viable. Creating API calls for real hashes that coexist with the current ones would be a better solution.

**Comment by commy2** [comment]
Real hashes as in using LOCATIONS with string keys? Converting objects to strings?

Two LOCATIONS can do the trick making the object key the value of a string key LOCATION.

**Comment by esteldunedain** [comment]
> Real hashes as in using LOCATIONS with string keys? 

yes

> Converting objects to strings? Two LOCATIONS can do the trick making the object key the value of a string key LOCATION.

I don't think that'd work reliably

**Comment by commy2** [comment]
PR still has the same problems as the other one, tag WIP

**Pull request merged**
