### PR TITLE
Change local keyword to private.

### PR DESCRIPTION
**Pull request by NouberNou**
Fixes error in current dev branch releases where keyword is already changed.

Should not be merged until A3 release updates.

### CODE REVIEW

**Comment by jonpas** [comment]
:+1:

**Comment by commy2** [comment]
remove extra spaces

**Comment by Killswitch00** [comment]
The migration away from using the `local` keyword could be done in two stages while keeping compatibility with 1.52:

Stage 1: `local _var = <value>` -> `private "_var"; _var = <value>`
Stage 2: `private "_var"; _var = <value>` -> `private _var = <value>`

After stage 1, one could do a patch release of CBA before A3 1.54 is out.

**Comment by commy2** [comment]
step 1: https://github.com/CBATeam/CBA_A3/pull/203
step 2: https://github.com/CBATeam/CBA_A3/pull/204

**Comment by jonpas** [comment]
Seems like Arma update will be released this week, so this might not really be worth it.

**Comment by Killswitch00** [comment]
The value of doing it would be doing proactive maintenance to make the transition to 1.54 trouble-free for users of CBA. 

Not doing it means we will have to be reactive and issue a fixed CBA after 1.54 breaks CBA.

Consider the public reaction to the two alternatives and the fact that getting a "fix" out ight take some time after 1.54 hits Steam.

**Comment by jonpas** [comment]
Yes, but how is stage 1 going to help this in the first place if you don't update CBA before 1.54 hits?

Not saying there is anything wrong with it, it would work perfectly, but current CBA won't work with 1.54 due to `local` keyword being used in the first place, and if you don't update it until 1.54 it will be broken either way.

**Comment by Killswitch00** [comment]
#203 is now merged, so a pre-1.54 CBA release is now possible.

**Comment by PabstMirror** [comment]
Can probably close and just use #204

**Comment by Killswitch00** [comment]
Yeah, #203 and later #204 will do what this one does.

**Pull request closed without merging**
