### PR TITLE
Put tags in CfgMusic.hpp into quotes

### PR DESCRIPTION
**Pull request by R3voA3**
Put tags in CfgMusic.hpp into quotes

Was suggested by @dedmen in https://github.com/CBATeam/CBA_A3/issues/1024

### CODE REVIEW

**Comment by commy2** [comment]
- Opening curly brackets should be at EOL not a new line just for them.
- What is the point of this file anyway? Are these not all base game classes?
- `theme` entry is just copy pasted from the base game config?

**Comment by dedmen** [comment]
>What is the point of this file anyway? Are these not all base game classes?

Yes but I think we are just adding tags to the new music stuff thingy?
When I looked at the music PR this stuff made sense I guess.

**Comment by dedmen** [comment]
>Removed double quotes from some theme entries.

Well as you can see you clearly can't trust my reviews 🥇

**Comment by RevoArma3** [comment]
There are a few tracks missing. Should I add them aswell?

**Pull request merged**
