### PR TITLE
Fix dancing AI (#551)

### PR DESCRIPTION
**Pull request by SilentSpike**
~~Some sort of conflict between `disableAI "PATH"` and `setUnitPos "UP"`~~
A bug in `setUnitPos "UP"` causes AI to dance when engaged (repeatedly trying to lower their profile but can't I assume)

### CODE REVIEW

**Comment by commy2** [comment]
Honestly, I liked `doStop` more. It didn't have permanent effects, so the AI could be given other waypoints / orders after they garrisoned a building.

**Comment by SilentSpike** [comment]
I was under the impression `doStop` did have permanent effects unless you executed specific script commands on the AI afterwards? (just like `disableAI "PATH"` but much more hacky).

**Comment by SilentSpike** [comment]
Decided to look into `doStop` for you, it actually causes the same dancing bug when used with `setUnitPos` :cry:

**Comment by commy2** [comment]
Hmm. Only alternative is https://community.bistudio.com/wiki/setUnitPosWeak, but that will be overruled by the AI FSM, so there is not much point in using it.

**Comment by SilentSpike** [comment]
It could work because they'd be detached from their formation with `doStop`, however if it did work I have a feeling it would cause the same problem

**Comment by ShizCalev** [comment]
Not sure if this is a CBA issue or an ACE one. With this change, when issuing the defend area command to units, once the patrolling units hit their cycle waypoint, all the units whom were in buildings abandon their posts and rejoin formation to take up patrol.

**Comment by commy2** [comment]
I think that is the expected behavior though. If a waypoint is finished, the whole group should begin with the next waypoint.

**Comment by ShizCalev** [comment]
Previous behavior was that issuing Defend Area would have units garrison buildings in the area, with a 7% chance of a unit going onto a patrol around the area. Once the patrol group finished through all waypoints and hit the cycle, they would repeat the same patrol with the same select units, and the rest would stay garrisoned (since pathing was disabled on the ones in the buildings.)

Now the behavior is that units garrison buildings, 7% chance at patrolling, however once the patrol group reaches the final waypoint and hit the cycle, all units leave their buildings and start patrolling the area in a formation.

**Comment by commy2** [comment]
That wasn't the case before @SilentSpike changed the taskDefend module / waypoint in the first place.
We cannot use `disableAI "PATH"` as it's broken.
I think placing waypoints after any of these taskX waypoints is undefined behavior.

**Comment by ShizCalev** [comment]
May I ask how `disableAI "PATH"` is broken? I know `setUnitPos "UP"` is, however this is the only I've heard about disableAI (and there are a couple other mods that I use that that information would be relevant for.)

I tired out replacing `doStop _unit;` with `disableAI "PATH"` and the AI seem to stay in the buildings as intended, and shoot freely as desired.

**Comment by commy2** [comment]
Yeah, my bad. `setUnitPos` is broken. However, units being stuck after a taskDefend waypoint is not intentional either.

**Pull request merged**
