### PR TITLE
make import editbox resize while editing it

### PR DESCRIPTION
**Pull request by commy2**
**When merged this pull request will:**
- automatically resize it
- give it a minimum height of the background

### CODE REVIEW

**Comment by bux** [comment]
When pasting a lot of settings the scrollbar behaves weird:
https://youtu.be/hP-9XkjtmTQ

**Comment by commy2** [comment]
I don't know how one could fix that. I fear a scrollbar is not feasible for the import version.

**Comment by commy2** [comment]
Nvm, I think I fixed it, lol.

**Comment by bux** [comment]
Confirmed, it works! 👍 

<kbd>Enter</kbd> seems to be blocked. But using <kbd>Shift</kbd> + <kbd>Enter</kbd> I can still add blank lines.

**Comment by jonpas** [comment]
> <kbd>Enter</kbd> seems to be blocked. But using <kbd>Shift</kbd> + <kbd>Enter</kbd> I can still add blank lines.

That's exactly how all code boxes work in Arma, eg. editor object init fields.

**Comment by commy2** [comment]
Woa, keyboard key symbols.

**Comment by bux** [comment]
>That's exactly how all code boxes work in Arma

Ok

**Pull request merged**
