### PR TITLE
JR: Do not blacklist long scopes on the short mg rails anymore, move …

### LINKED ISSUE #159: High zoom optics broken on all LMGs
CBA3 Version: v200150817-fixed

Mods:
    @CBA_A3

Description:

Most high zoom optics can not be used on any LMGs.
List:
- LMG_Zafir_F
- LMG_Mk200_F
- MMG_02_sand_F

When attempting to equip the scope in VA or via script, it won't appear.
Broken Scopes include:
- AMS
- DMS (optic_DMS)
- Kahila
- LRPS 
- MOS

Steps to reproduce:

Start Virtual Arsenal
Equip any lmg from list above 
Equip any of the optics above

Where did the issue occur?

    "Multiplayer", "Editor"

RPT log file:
n/a

### PR DESCRIPTION
**Pull request by robalo**
…that to optional pbo instead. Fixes #159.

### CODE REVIEW

**Comment by commy2** [comment]
Works :+1: Only problem is that these attachments are still shown in the arsenal, but are not useable (at least in current 1.55 dev).
I think that is a problem of the VA though.

**Comment by Killswitch00** [comment]
commy2, does the same no-usability issue happen if you start 1.55dev without CBA? If not, it is worth investigating further.

**Comment by robalo** [comment]
That behavior would be when the scope is incompatible (will happen with the optional pbo) and it's indeed a problem in VA which does not filter compatible items properly: http://feedback.arma3.com/view.php?id=23111

**Comment by Killswitch00** [comment]
Ah, OK - "good" news (read: it's not CBA)

**Comment by Killswitch00** [comment]
Hmm...that did not go where it should...

**Comment by robalo** [comment]
Might be my bad, did PR from diff between 2 of my branches.

**Pull request merged**
