### PR TITLE
Add missing includes for SQFC

### PR DESCRIPTION
**Pull request by Dahlgren**
**When merged this pull request will:**
- Fix ~4~3 failing compilations with ArmaScriptCompiler when using files in `include` folder

### CODE REVIEW

**Comment by commy2** [comment]
urg

**Comment by PabstMirror** [comment]
Looks like I meant to disable `fn_isDebugConsoleAllowed` but got it mixed up with `fnc_initExtendedDebugConsole`
so I can fix the sqfc.json and we don't need fn_isDebugConsoleAllowed in the `/include`

ref https://github.com/CBATeam/CBA_A3/pull/1450#issuecomment-846632661

**Comment by Dahlgren** [comment]
Nice, one less file 🙂

**Comment by commy2** [comment]
I don't like this. Who maintains these copy pasted files? Just pull them from the vanilla project files.

**Comment by jonpas** [comment]
Commy, they are includes for build tools, so P-drive is not required. You don't have to use them.

**Review by jonpas — APPROVED** [review]

**Pull request merged**
