### PR TITLE
Optimize Functions by Using 1.55 Select Syntax

### PR DESCRIPTION
**Pull request by 654wak654**
**When merged this pull request will:**
- Make `CBA_fnc_select` and `CBA_fnc_reject` smaller by completely replacing them with the identical syntax of the select command.

### CODE REVIEW

**Comment by commy2** [comment]
This means that you no longer can use `_this` and more importantly `_forEachIndex` with these functions. I think we should just deprecate them and leave them as they are.

**Comment by 654wak654** [comment]
You still have `_this`, didn't consider `_forEachIndex`.

**Comment by commy2** [comment]
Yes you can. But why would you? Idk. I still think:
>we should just deprecate them and leave them as they are.

**Comment by 654wak654** [comment]
You should, doubt many addons are using it anyway.

**Comment by 654wak654** [comment]
Remember to deprecate 'em.

**Pull request closed without merging**
