### PR TITLE
remove productVersion checks/ IS_LINUX macros

### PR DESCRIPTION
**Pull request by commy2**
removes bwc stuff that no longer applies in for v3.0.0

### CODE REVIEW

**Comment by commy2** [comment]
CRLF

**Comment by Killswitch00** [comment]
We may need this mechanism in the future when the ports catch up and then are left behind again.

**Comment by commy2** [comment]
true, but then we can just go back in git history to get the linux.pbo

**Comment by Killswitch00** [comment]
Fair enough.

**Comment by commy2** [comment]
testing ...

**Comment by commy2** [comment]
works

**Pull request merged**
