### PR TITLE
Add Garrison/Patrol ratio parameter

### PR DESCRIPTION
**Pull request by 50KAL0V**
- Slight increase to the default, but this way users can tweak to allow for more of a "Defence" rather then just another garrison style script.

- Added the new parameter, description and edited text above its use.

### CODE REVIEW

**Comment by commy2** [comment]
Should probably do the following as well:

- Add this as parameter to the module:
https://github.com/CBATeam/CBA_A3/blob/master/addons/modules/CfgVehicles.hpp#L102
https://github.com/CBATeam/CBA_A3/blob/master/addons/modules/fnc_moduleDefend.sqf

- Change the default for the waypoint version to 80% too:
https://github.com/CBATeam/CBA_A3/blob/master/addons/ai/fnc_waypointGarrison.sqf#L34

**Comment by SilentSpike** [comment]
I feel like this is slightly misleading, since it's not actually a ratio (0.8 != 80% of units will garrison).

**Comment by SilentSpike** [comment]
It would probably be better to make the `_patrol` parameter accept either boolean or a percentage chance value for an implementation such as this.

**Comment by commy2** [comment]
>it's not actually a ratio (0.8 != 80% of units will garrison).

It is for large amount of units.

**Comment by SilentSpike** [comment]
On average true (assuming `random` is uniform distribution which I've never checked), but you could in practise get the exact opposite ratio than expected

**Comment by commy2** [comment]
The function header should state that it's a probability per unit (if it is, not sure).

**Comment by 50KAL0V** [comment]
Before i break it all horribly not being much of a code and github guru

Whats the best way for me to submit those other changes? should i edit in the branch its created or create new pull requests?

Also regarding the modules, will the "typeName" be number?

**Comment by commy2** [comment]
Edit your branch and push to your repository. It will retrieve the new changes here automatically.

**Comment by commy2** [comment]
>Also regarding the modules, will the "typeName" be number? Or still called a Float???
Probably "NUMBER"

**Comment by 50KAL0V** [comment]
cheers, will get on that

**Comment by commy2** [comment]
Status?

**Comment by SilentSpike** [comment]
I had another idea along these lines recently: a parameter could be added for the percentage of units who will `disableAI "PATH"` (default 0%) that way people who want that behaviour can enable it too

**Comment by Killswitch00** [comment]
This still needs the changes in other files that commy2 noted on Jan 13

**Comment by SilentSpike** [comment]
I'd be happy to re-implement this if @50KAL0V has gone AWOL 😆

**Comment by Killswitch00** [comment]
That'll work. Also, it was never explained why the default probability was lowered from 0.93 to 0.8.

**Comment by Killswitch00** [comment]
Re-implemented in #702

**Pull request closed without merging**
