### PR TITLE
Documentation - Update fnc_waitUntilAndExecute-sqf.html

### PR DESCRIPTION
**Pull request by OverlordZorn**
Update Documentation in line with #1711

### CODE REVIEW

**Comment by PabstMirror** [comment]
this might be replaced with #1714 ?

**Comment by jokoho48** [comment]
> this might be replaced with #1714 ?

when https://github.com/CBATeam/CBA_A3/pull/1711 is merged I will rerun the docs build on #1714 so this is than replaced

**Comment by OverlordZorn** [comment]
i assume i can close the pr now, right?

**Comment by jokoho48** [comment]
> i assume i can close the pr now, right?

yes docs have been rebuild with the change of #1711

**Pull request closed without merging**
