### PR TITLE
Add GitHub files

### PR DESCRIPTION
**Pull request by jonpas**
**When merged this pull request will:**
- Add `.github` files
- CONTRIBUTING.md
- ISSUE_TEMPLATE.md
- PULL_REQUEST_TEMPLATE.md

### CODE REVIEW

**Comment by jonpas** [comment]
Why do I have a feeling this is wrong `master`.

**Comment by Killswitch00** [comment]
Uhm...was this supposed to go into `CBATeam:master`?

**Comment by jonpas** [comment]
Yes, that is just how GitHub displays it for pull requests originating from a fork. Whatever bux did that one time where it went to oblivion, it was something else.

**Comment by bux578** [comment]
:cry:

**Pull request merged**
