### PR TITLE
Add subString for Closer Fitting to Programming Standarts

### PR DESCRIPTION
**Pull request by jokoho48**
This is subString work like more than C# Substring Method and is with that closer to a normal Programming language

### CODE REVIEW

**Comment by Killswitch00** [comment]
The description of the _length parameter is still "lenth"

**Comment by jokoho48** [comment]
Yep done sry for that miss this

**Comment by Killswitch00** [comment]
I just noticed you have altered the existing function file and added "(deprec)" to the comment. That function is not and will not be deprecated.

**Comment by Killswitch00** [comment]
Bump for the author. Joko, please address the two points above so we can merge this for the upcoming release. Thanks for the contribution!

**Comment by jokoho48** [comment]
ok Done

**Comment by Killswitch00** [comment]
fnc_substr.sqf is missing

**Comment by jokoho48** [comment]
sometimes i have Git

**Comment by Killswitch00** [comment]
Excellent. Now, do a ```sed -i 's/substrig_new/substr/g' fnc_substr.sqf :-)

(Replace "substring_new" with "substr" inside fnc_substr.sqf

**Comment by jokoho48** [comment]
i normaly use SVN tortoise and this show new Files too and i dont must add first

**Comment by jokoho48** [comment]
now?

**Comment by Killswitch00** [comment]
The comment ```Check if _length is set else extrakt string to end``` has the word "extract" misspelled.

**Comment by jokoho48** [comment]
ok

**Pull request merged**
