### PR TITLE
Optimize if statement in state machine

### PR DESCRIPTION
**Pull request by jameslkingsley**
**When merged this pull request will:**
- Title
- Saves 0.0002ms

### CODE REVIEW

**Comment by PabstMirror** [comment]
Tag @BaerMitUmlaut

**Comment by BaerMitUmlaut** [comment]
:shipit:

**Comment by commy2** [comment]
>Saves 0.0002ms

:facepalm:

**Comment by PabstMirror** [comment]
That's 1 extra frame every 30 minutes!
How can you down free frames?

**Pull request merged**
