### PR TITLE
joint rails - enoch attachment classes compatibility - Variant A

### PR DESCRIPTION
**Pull request by commy2**
This PR fixes the following UBC classes since Arma 1.94 = Enoch:

```
 9:02:51 Cannot delete class PointerSlot, it is referenced somewhere (used as a base class probably).
 9:02:51 Updating base class MuzzleSlot_65->asdg_MuzzleSlot_65, by x\cba\addons\jr\config.cpp/CfgWeapons/arifle_MX_F/WeaponSlotsInfo/MuzzleSlot/ (original (no unload))
 9:02:51 Updating base class PointerSlot_Rail->asdg_FrontSideRail, by x\cba\addons\jr\config.cpp/CfgWeapons/arifle_MX_F/WeaponSlotsInfo/PointerSlot/ (original (no unload))
 9:02:51 Updating base class MuzzleSlot_65->asdg_MuzzleSlot_65, by x\cba\addons\jr\config.cpp/CfgWeapons/arifle_MX_GL_F/WeaponSlotsInfo/MuzzleSlot/ (original (no unload))
 9:02:51 Updating base class PointerSlot_Rail->asdg_FrontSideRail, by x\cba\addons\jr\config.cpp/CfgWeapons/arifle_MX_GL_F/WeaponSlotsInfo/PointerSlot/ (original (no unload))
 9:02:51 Updating base class PointerSlot_Rail->asdg_FrontSideRail, by x\cba\addons\jr\config.cpp/CfgWeapons/arifle_MX_SW_F/WeaponSlotsInfo/PointerSlot/ (original (no unload))
 9:02:51 Updating base class PointerSlot_Rail->asdg_FrontSideRail, by x\cba\addons\jr\config.cpp/CfgWeapons/arifle_MXM_F/WeaponSlotsInfo/PointerSlot/ (original (no unload))
 9:02:51 Updating base class PointerSlot->asdg_FrontSideRail, by x\cba\addons\jr\config.cpp/CfgWeapons/arifle_AK12_base_F/WeaponSlotsInfo/PointerSlot/ (original a3\weapons_f_exp\rifles\ak12\config.bin)
 9:02:51 Updating base class UnderBarrelSlot_rail->asdg_UnderSlot, by x\cba\addons\jr\config.cpp/CfgWeapons/arifle_AK12_F/WeaponSlotsInfo/UnderBarrelSlot/ (original (no unload))
```

This means that we drop Joint Rails support for muzzle and pointer slots of the MX series, and pointer and bipod support for the AK12 series.

The benefit of this is, that addons that only add items to the new vanilla attachment classes and no JR, will not be broken by CBA_A3 in the future.

The drawback of this is, that addons that already add items to these specific joint rails classes, will have to add their items to both the new BI classes and the CBA_A3 joint rails classes to support both MX and AK12, as well as future third party classes coping these vanilla attachment classes, as well as old third party classes that already use the joint rails classes.

### CODE REVIEW

**Comment by commy2** [comment]
May need to check if AK12 public classes not overwrite the attachment classes we have here, which means I'd have to adjust this PR.

**Comment by dedmen** [comment]
Modders are already used to adding to two classes for magazineWells.
However now modders might have to decide whether to inherit from the CBA class, or the vanilla class.
And for now, mod attachments then won't work on stuff that uses vanilla JR. Which I personally don't care about. If you run mod weapons with mod attachments, you prolly don't use vanilla weapons anyway

**Comment by commy2** [comment]
So, A or B?

**Comment by commy2** [comment]
Changed in magwells due to Enoch:
`DMR_01_base_F`, `EBR_base_F`, `DMR_03_base_F` and `DMR_06_base_F`:
```
asdg_MuzzleSlot_762 -> MuzzleSlot_762
```


`mk20_base_F` and `Tavor_base_F`:
```
asdg_MuzzleSlot_556 -> MuzzleSlot_556
```


`arifle_Katiba_Base_F` and `LMG_Mk200_F`:
```
asdg_MuzzleSlot_65 -> MuzzleSlot_65
```


`arifle_MX_Base_F`:
```
asdg_MuzzleSlot_65 -> MuzzleSlot_65
asdg_FrontSideRail -> PointerSlot_Rail
```


`arifle_AK12_base_F`, `arifle_AK12U_base_F` and `arifle_RPK12_base_F`:
```
asdg_MuzzleSlot_762R -> MuzzleSlot_762
asdg_OpticRail1913 -> CowsSlot_Rail
asdg_UnderSlot -> UnderBarrelSlot_rail
```

**Comment by commy2** [comment]
Done.

**Pull request merged**
