### PR TITLE
Add a Slower PFH that only checks every 5 secs to Player Events

### PR DESCRIPTION
**Pull request by jokoho48**
**When merged this pull request will:**
- Add a slower PFH to player EHs
- move Loadout, group and leader changed to the slower PFH

### CODE REVIEW

**Comment by PabstMirror** [comment]
What about if we still use the same EachFrame eh instead of adding the overhead of a new PFEH
```
// Do Fast Checks
if (GVAR(nextSlowCheck) < CBA_missionTime) then {
    GVAR(nextSlowCheck) = GVAR(nextSlowCheck) + 5;
    // Do Slow Checks
};
```
5 second seems a little long for the loadout/inventory check IMHO
e.g. ace_hearing, put on a helmet with hearing protection and you won't get audible feedback right away

**Comment by commy2** [comment]
I don't like this. I think it's not needed at all.

**Comment by SilentSpike** [comment]
I agree. If anything does this not add complexity to the PFH? Has performance difference been tested?

**Comment by jokoho48** [comment]
i made this because commy2 noticed in the slack that dont like it that group and leader gets checked everyframe. that is why i changed it so that its only checked 1 a sec

**Comment by Glowbal** [comment]
Is there a performance problem? If so, how much and why change these 3 events and not others? 

If not, I feel this risks the responsiveness of dependent listeners and affect gameplay in a negative manner.

**Pull request closed without merging**
