### PR TITLE
JAM update for 1.86

### PR DESCRIPTION
**Pull request by robalo**
Updates instead of overriding vanilla magwells.
Inherit from existing vanilla magwells.
Remove leading spaces.

### CODE REVIEW

**Comment by robalo** [comment]
Just to see what I was talking about in #1030

**Comment by robalo** [comment]
I see what you mean. Existing implementation can override the inheritance. Could've left the vanilla mags un-commented in the CBA child classes to avoid losing the, that way.

**Comment by dedmen** [comment]
Did you test if these actually work? As I said, inheritance was broken and reyhard never told me if he fixed it.

**Comment by PabstMirror** [comment]
```
    class arifle_MX_test_F : arifle_MX_SW_F {
        displayName = "0 Test Gun";
        scope = 2;
        magazineWell[] = {"CBA_65x39_MX"};
        magazines[] = {};
    };
```
Config wise it should work, but I can't load the mag in
image


Good call @dedmen, biki has same warning

`// It's possible to add new arrays to class but for now inheritance (i.e. STANAG_556x45_New: STANAG_556x45 {};)  is not supported `

**Comment by robalo** [comment]
This PR is a fail, scrap it, concentrate on #1030

**Pull request closed without merging**
