### PR TITLE
Tools - Show version when installing HEMTT

### PR DESCRIPTION
**Pull request by PabstMirror**
Small QOL (also newest hemtt has lower version number?)

### CODE REVIEW

**Comment by jonpas** [comment]
Make sure it works with PowerShell 3.0 (not higher).

> Small QOL (also newest hemtt has lower version number?)

Yes, we were on a development version. There is no difference to the user right now.

**Comment by jonpas** [comment]
Looks like HEMTT wasn't update on dockerhub yet, let's wait for that, I poked Brett.

**Comment by jonpas** [comment]
Works fine with PowerShell 3.0.

**Comment by commy2** [comment]
Merge?

**Comment by jonpas** [comment]
No

> Looks like HEMTT wasn't update on dockerhub yet, let's wait for that, I poked Brett.

**Comment by jonpas** [comment]
Builds going and commit build artifacts now available! :tada:

**Pull request merged**
